/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'surface':                  '#f8f9fa',
        'surface-dim':              '#d9dadb',
        'surface-bright':           '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f3f4f5',
        'surface-container':        '#edeeef',
        'surface-container-high':   '#e7e8e9',
        'surface-container-highest':'#e1e3e4',
        'on-surface':               '#191c1d',
        'on-surface-variant':       '#414844',
        'inverse-surface':          '#2e3132',
        'inverse-on-surface':       '#f0f1f2',
        'outline':                  '#717973',
        'outline-variant':          '#c1c8c2',
        'surface-tint':             '#3f6653',
        'surface-variant':          '#e1e3e4',
        'primary':                  '#012d1d',
        'on-primary':               '#ffffff',
        'primary-container':        '#1b4332',
        'on-primary-container':     '#86af99',
        'inverse-primary':          '#a5d0b9',
        'primary-fixed':            '#c1ecd4',
        'primary-fixed-dim':        '#a5d0b9',
        'on-primary-fixed':         '#002114',
        'on-primary-fixed-variant': '#274e3d',
        'secondary':                '#934b00',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#fd8603',
        'on-secondary-container':   '#5f2f00',
        'secondary-fixed':          '#ffdcc4',
        'secondary-fixed-dim':      '#ffb781',
        'on-secondary-fixed':       '#301400',
        'on-secondary-fixed-variant':'#703800',
        'tertiary':                 '#002a38',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#004155',
        'on-tertiary-container':    '#72aec9',
        'tertiary-fixed':           '#bde9ff',
        'tertiary-fixed-dim':       '#93cfeb',
        'on-tertiary-fixed':        '#001f2a',
        'on-tertiary-fixed-variant':'#004d64',
        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',
        'background':               '#f8f9fa',
        'on-background':            '#191c1d',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm':      '0.25rem',
        'md':      '0.75rem',
        'lg':      '1rem',
        'xl':      '1.5rem',
        'full':    '9999px',
      },
      spacing: {
        'xs':             '4px',
        'sm':             '8px',
        'base':           '8px',
        'md':             '16px',
        'lg':             '24px',
        'xl':             '48px',
        'gutter':         '20px',
        'margin-mobile':  '16px',
        'margin-desktop': '32px',
        'container-max':  '1280px',
      },
      fontFamily: {
        'jakarta': ['"Plus Jakarta Sans"', 'sans-serif'],
        'vietnam': ['"Be Vietnam Pro"', 'sans-serif'],
      },
      fontSize: {
        'label-sm':          ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md':          ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-md':           ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg':           ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md':       ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile':['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg':       ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'headline-xl':       ['40px', { lineHeight: '48px', fontWeight: '700', letterSpacing: '-0.02em' }],
      },
      boxShadow: {
        'card':     '0 2px 10px rgba(27, 67, 50, 0.08)',
        'elevated': '0 4px 20px rgba(27, 67, 50, 0.12)',
        'orange':   '0 4px 20px rgba(253, 134, 3, 0.30)',
      },
    },
  },
  plugins: [],
}
